#!/bin/bash
#


BASE_DIR="$( cd "$( dirname "$( readlink -f "${BASH_SOURCE[0]}")" )" && pwd )";
PACKAGE_DIR=${BASE_DIR}/packages;
INSTALL_DEST=${INSTALL_DEST:-/};

# Set script colours
CLRED="\e[91m";
CNORM="\e[0m";


# Install the package
install_package() {
    if [[ ! -z ${1} ]]; then
        PACKAGE=${1};
        # Install defaults
        if [[ -d ${PACKAGE_DIR}/${PACKAGE}/defaults ]]; then
            echo "    [${PACKAGE}] Installing defaults to ${INSTALL_DEST%/}/defaults/${PACKAGE}";
            mkdir -p ${INSTALL_DEST%/}/defaults/${PACKAGE};
            cp -rf ${PACKAGE_DIR}/${PACKAGE}/defaults/* ${INSTALL_DEST%/}/defaults/${PACKAGE}/;
        fi
        # Install etc
        if [[ -d ${PACKAGE_DIR}/${PACKAGE}/etc ]]; then
            echo "    [${PACKAGE}] Installing etc to ${INSTALL_DEST%/}/etc";
            mkdir -p ${INSTALL_DEST%/}/etc;
            cp -rf ${PACKAGE_DIR}/${PACKAGE}/etc/* ${INSTALL_DEST%/}/etc/;
        fi
        # Install usr
        if [[ -d ${PACKAGE_DIR}/${PACKAGE}/usr ]]; then
            echo "    [${PACKAGE}] Installing usr to ${INSTALL_DEST%/}/usr";
            mkdir -p ${INSTALL_DEST%/}/usr;
            cp -rf ${PACKAGE_DIR}/${PACKAGE}/usr/* ${INSTALL_DEST%/}/usr/;
        fi
    fi
}


# Run
if [[ -z ${S6_INIT_PACKAGES} ]]; then
    echo -ne "${CLRED}";
    echo
    echo "!!WARNING!! No s6-init packages specified.";
    echo
    echo "Ensure you have the 'S6_INIT_PACKAGES' ARG configured in your Dockerfile.";
    echo "Example:";
    echo "    ARG S6_INIT_PACKAGES='nginx'";
    echo
    echo -ne "${CNORM}";
    exit 1
fi
for PACKAGE in ${S6_INIT_PACKAGES}; do
    echo "**** Installing package: ${S6_INIT_PACKAGES} ****";
    install_package ${PACKAGE};
done
